version: '3'

services:
  db:
    image: postgres:latest
    container_name: task-management-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      # Expose weird port on host to avoid collisions
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

  app:
    image: openjdk:21-jdk-slim
    container_name: task-management-app
    command: ./gradlew bootRun
    volumes:
      - ./:/app
    expose:
      - 8080
    ports:
      # Expose weird port on host to avoid collisions
      - 8080:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_FLYWAY_URL: jdbc:postgresql://db:5432/postgres
      SPRING_FLYWAY_USER: postgres
      SPRING_FLYWAY_PASSWORD: postgres
      APP_AUTH_TOKEN_SECRET: JTUlYXGntwjw5DFFEFJy
      APP_AUTH_REFRESH_TOKEN_SECRET: DkbHtJKhv1PNi4WYqvWc
    networks:
      - app-network
    working_dir: /app
    restart: always

volumes:
  dbdata:

networks:
  app-network: